# PyCity Schools Analysis

* As a whole, schools with higher budgets, did not yield better test results. By contrast, schools with higher spending per student actually (\$645-675) underperformed compared to schools with smaller budgets (<\$585 per student).

* As a whole, smaller and medium sized schools dramatically out-performed large sized schools on passing math performances (89-91% passing vs 67%).

* As a whole, charter schools out-performed the public district schools across all metrics. However, more analysis will be required to glean if the effect is due to school practices or the fact that charter schools tend to serve smaller student populations per school. 
---

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [557]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt

df_schools_data =pd.read_csv("Resources/schools_complete.csv")     #short cut to avoid the entire pd read
df_students_data = pd.read_csv("Resources/students_complete.csv")



#df_schools_data = pd.merge(students_data,schools_data)
df_combined = pd.merge(df_schools_data,df_students_data,how ="left", on= ["school_name","school_name"])
df_combined

df_schools_data.rename({"name" : "school name"}, axis=1, inplace=True)

newdf_schools_data = df_schools_data.copy
#df_combined = pd.merge(df_students_data, df_schools_data, how="left", on=["school_name", "school_name"])
#df_combined
df_schools_data
df_students_data

# student data is longer 
# # File to Load (Remember to Change These)
# school_data_to_load = "Resources/schools_complete.csv"
# student_data_to_load = "Resources/students_complete.csv"

# # Read School and Student Data File and store into Pandas Data Frames
# school_data = pd.read_csv(school_data_to_load)
# student_data = pd.read_csv(student_data_to_load)

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84
5,5,Bryan Miranda,M,9th,Huang High School,94,94
6,6,Sheena Carter,F,11th,Huang High School,82,80
7,7,Nicole Baker,F,12th,Huang High School,96,69
8,8,Michael Roth,M,10th,Huang High School,95,87
9,9,Matthew Greene,M,10th,Huang High School,96,84
10,10,Andrew Alexander,M,10th,Huang High School,90,70
11,11,Daniel Cooper,M,10th,Huang High School,78,77
12,12,Brittney Walker,F,9th,Huang High School,64,79
13,13,William Long,M,9th,Huang High School,71,79
14,14,Tammy Hebert,F,10th,Huang High School,85,67
15,15,Dr. Jordan Carson,M,11th,Huang High School,94,88
16,16,Donald Zamora,M,9th,Huang High School,88,55
17,17,Kimberly Santiago,F,9th,Huang High School,74,75
18,18,Kevin Stevens,M,9th,Huang High School,64,69
19,19,Brandi Lyons,F,9th,Huang High School,89,80
20,20,Lisa Davis,F,10th,Huang High School,91,89
21,21,Kristen Lopez,F,10th,Huang High School,90,77
22,22,Kimberly Stewart,F,11th,Huang High School,99,84
23,23,Christopher Parker,M,9th,Huang High School,81,68
24,24,Chelsea Griffith,F,11th,Huang High School,85,73
25,25,Cesar Morris,M,9th,Huang High School,92,70
26,26,Melanie Decker,F,9th,Huang High School,63,85
27,27,Tracey Oconnor,F,10th,Huang High School,80,58
28,28,Kelly James,F,11th,Huang High School,73,55
29,29,Nicole Brown,F,12th,Huang High School,90,88
...,...,...,...,...,...,...,...
39140,39140,Cheyenne Hernandez,F,9th,Thomas High School,76,99
39141,39141,Jonathan Sullivan,M,10th,Thomas High School,86,93
39142,39142,Deborah Higgins DDS,F,10th,Thomas High School,96,83
39143,39143,Steven Jackson,M,11th,Thomas High School,71,93
39144,39144,Cristian Webster,M,12th,Thomas High School,77,87
39145,39145,Audrey Fry,F,10th,Thomas High School,94,74
39146,39146,Michael Carroll,M,9th,Thomas High School,69,95
39147,39147,Raymond Hawkins,M,10th,Thomas High School,88,81
39148,39148,Christopher Wilson,M,10th,Thomas High School,89,89
39149,39149,Glenda Fletcher,F,11th,Thomas High School,82,93
39150,39150,Jennifer Hamilton,F,11th,Thomas High School,80,75
39151,39151,Shannon Williams,F,10th,Thomas High School,84,73
39152,39152,Lori Moore,F,9th,Thomas High School,98,84
39153,39153,William Hubbard,M,9th,Thomas High School,80,75
39154,39154,Bradley Johnson,M,12th,Thomas High School,91,71
39155,39155,John Brooks,M,10th,Thomas High School,92,98
39156,39156,Stephanie Contreras,F,11th,Thomas High School,79,95
39157,39157,Kristen Gonzalez,F,9th,Thomas High School,79,94
39158,39158,Kari Holloway,F,10th,Thomas High School,87,90
39159,39159,Kimberly Cabrera,F,11th,Thomas High School,85,72
39160,39160,Katie Weaver,F,11th,Thomas High School,89,86
39161,39161,April Reyes,F,10th,Thomas High School,70,84
39162,39162,Derek Weeks,M,12th,Thomas High School,94,77
39163,39163,John Reese,M,11th,Thomas High School,90,75
39164,39164,Joseph Anthony,M,9th,Thomas High School,97,76
39165,39165,Donna Howard,F,12th,Thomas High School,99,90
39166,39166,Dawn Bell,F,10th,Thomas High School,95,70
39167,39167,Rebecca Tanner,F,9th,Thomas High School,73,84
39168,39168,Desiree Kidd,F,10th,Thomas High School,99,90
39169,39169,Carolyn Jackson,F,11th,Thomas High School,95,75

## District Summary

* Calculate the total number of schools

* Calculate the total number of students

* Calculate the total budget

* Calculate the average math score 

* Calculate the average reading score

* Calculate the overall passing rate (overall average score), i.e. (avg. math score + avg. reading score)/2

* Calculate the percentage of students with a passing math score (70 or greater)

* Calculate the percentage of students with a passing reading score (70 or greater)

* Create a dataframe to hold the above results

* Optional: give the displayed data cleaner formatting

In [300]:
# df_Total = df_combined.groupby ['school_name'].sum()
# df_Total
metrics_list = []
value_list = []
students_value = []
money_list = []
Math_list =[]
Reading_list =[]
#Percent_math= []



# Percent_reading =[]
#Overall_percent = (Math_list+Reading_list)
#Percent_total =df_combined.loc[df_combined]['Over_']

#Overall_percent = (Math_list + Reading_list ) /2
# df_school_total = "School Total"
# school_total_value = len(df_combined['school_name'].unique())
#metrics_list.append("School Total")
value_list.append(len(df_combined['school_name'].unique()))
students_value.append (len(df_combined['Student ID'].unique()))
money_list.append(sum(df_combined['budget'].unique()))
Math_list.append(df_combined['math_score'].mean())
Reading_list.append(df_combined['reading_score'].mean())

Percent_Math = df_combined.loc[df_combined['math_score'] >=70,:]
MathPct = Percent_Math['math_score'].count() / students_value * 100
#Percent_math.append(len([df_combined['math_score']>=70])/students_value

Percent_Reading = df_combined.loc[df_combined['reading_score'] >=70,:]
ReadingPct = Percent_Reading['reading_score'].count() / students_value * 100


overall_passing_rate = (ReadingPct + MathPct) / 2

#Overall_percent = (Math_list + Reading_list ) /2

#len(school_data_complete[school_data_complete['math_score'] >= 70])/number_of_students

# #Percent_math = df.groupby(df_combined['math_score'].agg({'% Passing Math': 'sum'}))
#Percent_reading = df.groupby(df_combined['reading_score'].agg({'% Passing Reading': 'sum'}))
#Overall_percent = df.groupby(df_combined[''].unique()))

# cols = ['<80%', '80-90', '>90']
# df[cols] = df[cols].div(df[cols].sum(axis=1), axis=0).multiply(100)

df= pd.DataFrame({'School Total':value_list,'Total Students': students_value,
                   'Total Budget':money_list,'Average Math Score': Math_list,
                   'Average Reading Score':Reading_list,'% Passing Math': MathPct,
                   '% Passing Reading':ReadingPct,'% Overall Passing Rate':overall_passing_rate})

dist_sum = df[['School Total', 
                             "Total Students", 
                             "Total Budget", 
                             "Average Math Score", 
                             "Average Reading Score", 
                             '% Passing Math', 
                             '% Passing Reading', 
                             '% Overall Passing Rate']]

#'Values':value_list})

#df.iloc[0:6] if you want specific forms 

#df.loc[(([]>7)& another quotation)] to return columns you want 

#df.head () first 5 tables 
df

,School Total,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
0,15,39170,24649428,78.985371,81.87784,74.980853,85.805463,80.393158

## School Summary

* Create an overview table that summarizes key metrics about each school, including:
  * School Name
  * School Type
  * Total Students
  * Total School Budget
  * Per Student Budget
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)
  
* Create a dataframe to hold the above results

In [509]:
#we have the total students and total school budget already so there is no need to calc it again 
#instead of using variables ; print totals by associating a graph 

#newdf_schools_data

# Dependencies and Setup
import pandas as pd
import numpy as np
import csv


df_schools_data =pd.read_csv("Resources/schools_complete.csv")     #short cut to avoid the entire pd read
df_students_data = pd.read_csv("Resources/students_complete.csv")

df_schools = df_schools_data
df_students =df_students_data
#groups by school
df_schools_data= df_schools.set_index('school_name').groupby(['school_name'])

#school types
sch_distr = df_combined.set_index('school_name')['type']

#total students
stu_per_sch = df_students['Student ID'].count()
#total school budget
tot_sch_budget = df_combined.set_index('school_name')['budget']
#per student budget 
Per_Student_Budget['Per Student Budget']= df_schools['budget']/df_schools['size']
#stu_bug['Per Student Budget']= df_combined ['budget']/df_combined ['size']

avg_list=df_combined['math_score'].mean()

avg_read= df_combined['reading_score'].mean()

Percent_Math = []
Percent_Reading = []
Percent_Math = df_combined.loc[df_combined['math_score'] >=70,:]
Math = Percent_Math['math_score'].count() / students_value * 100

# #Percent_math.append(len([df_combined['math_score']>=70])/students_value

Percent_Reading = df_combined.loc[df_combined['reading_score'] >=70,:]
Reading = Percent_Reading['reading_score'].count() / students_value * 100


overall_passing = (len(Math + Reading)) / 2




#print table

school_summary = pd.DataFrame({
    "School Type": sch_distr,
    "Total Students": stu_per_sch,
    "Total School Budget": tot_sch_budget,
    "Per Student Budget" : sch_distr,
    'Average Math Score': avg_list,
    'Average Reading Score': avg_read,
    '% Passing Math': sch_distr,
    '% Passing Reading': sch_distr,
    '% Overall Passing Rate': overall_passing})


# pd.DataFrame({
#     "Total Schools": [number_of_schools], "Total Students": [number_of_students], 
#     "Total Budget": [total_budget], "Average Math Score": [avg_math_score] ,
#     'Average Reading Score': [avg_reading_score], '% Passing Math': [math_percent*100] ,
#     '% Passing Reading': [reading_percent*100],'% Overall Pass Rate': [passing_score]
# })

school_summary

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
school_name,,,,,,,,,
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
...,...,...,...,...,...,...,...,...,...
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5
Thomas High School,Charter,39170,1043130,Charter,78.985371,81.87784,Charter,Charter,0.5



## Top Performing Schools (By Passing Rate)

* Sort and display the top five schools in overall passing rate

In [511]:
top_performing = school_summary.sort_values(by=['% Overall Passing Rate'], ascending=False).head(5)

top_performing.head(5)

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
school_name,,,,,,,,,
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Rodriguez High School,District,39170,2547363,District,78.985371,81.87784,District,District,0.5
Rodriguez High School,District,39170,2547363,District,78.985371,81.87784,District,District,0.5
Rodriguez High School,District,39170,2547363,District,78.985371,81.87784,District,District,0.5
Rodriguez High School,District,39170,2547363,District,78.985371,81.87784,District,District,0.5

## Bottom Performing Schools (By Passing Rate)

* Sort and display the five worst-performing schools

In [512]:
worst_performing = school_summary.sort_values(by=['% Overall Passing Rate']).head(5)

worst_performing.head(5)

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
school_name,,,,,,,,,
Huang High School,District,39170,1910635,District,78.985371,81.87784,District,District,0.5
Rodriguez High School,District,39170,2547363,District,78.985371,81.87784,District,District,0.5
Rodriguez High School,District,39170,2547363,District,78.985371,81.87784,District,District,0.5
Rodriguez High School,District,39170,2547363,District,78.985371,81.87784,District,District,0.5
Rodriguez High School,District,39170,2547363,District,78.985371,81.87784,District,District,0.5

## Math Scores by Grade

* Create a table that lists the average Reading Score for students of each grade level (9th, 10th, 11th, 12th) at each school.

  * Create a pandas series for each grade. Hint: use a conditional statement.
  
  * Group each series by school
  
  * Combine the series into a dataframe
  
  * Optional: give the displayed data cleaner formatting

In [528]:
# grades_for_math = pd.pivot_table(df_students, values=['math_score'], index=['school_name'], 
#                                          columns=['grade'])
# grades_for_math = grades_for_math.reindex(labels=['9th',
#                                                                     '10th',
#                                                                     '11th',
#                                                                     '12th'], axis=1, level=1)

ninth_grd = df_students.loc[df_students['grade'] == '9th'].groupby('school_name')["math_score"].mean()
tenth_grd = df_students.loc[df_students['grade'] == '10th'].groupby('school_name')["math_score"].mean()
eleventh_grd = df_students.loc[df_students['grade'] == '11th'].groupby('school_name')["math_score"].mean()
twelfth_grd = df_students.loc[df_students['grade'] == '12th'].groupby('school_name')["math_score"].mean()

math_scores = pd.DataFrame({
        "9th": ninth_grd,
        "10th": tenth_grd,
        "11th": eleventh_grd,
        "12th": twelfth_grd
})
math_scores = math_scores[['9th', '10th', '11th', '12th']]
math_scores.index.name = "School"

math_scores

                             9th       10th       11th       12th
School
Bailey High School     77.083676  76.996772  77.515588  76.492218
Cabrera High School    83.094697  83.154506  82.765560  83.277487
Figueroa High School   76.403037  76.539974  76.884344  77.151369
Ford High School       77.361345  77.672316  76.918058  76.179963
Griffin High School    82.044010  84.229064  83.842105  83.356164
Hernandez High School  77.438495  77.337408  77.136029  77.186567
Holden High School     83.787402  83.429825  85.000000  82.855422
Huang High School      77.027251  75.908735  76.446602  77.225641
Johnson High School    77.187857  76.691117  77.491653  76.863248
Pena High School       83.625455  83.372000  84.328125  84.121547
Rodriguez High School  76.859966  76.612500  76.395626  77.690748
Shelton High School    83.420755  82.917411  83.383495  83.778976
Thomas High School     83.590022  83.087886  83.498795  83.497041
Wilson High School     83.085578  83.724422  83.195326  83.035794
Wright High School     83.264706  84.010288  83.836782  83.644986

## Reading Score by Grade

* Perform the same operations as above for reading scores

In [529]:

ninth_grd = df_students.loc[df_students['grade'] == '9th'].groupby('school_name')["reading_score"].mean()
tenth_grd = df_students.loc[df_students['grade'] == '10th'].groupby('school_name')["reading_score"].mean()
eleventh_grd = df_students.loc[df_students['grade'] == '11th'].groupby('school_name')["reading_score"].mean()
twelfth_grd = df_students.loc[df_students['grade'] == '12th'].groupby('school_name')["reading_score"].mean()

reading_scores = pd.DataFrame({
        "9th": ninth_grd,
        "10th": tenth_grd,
        "11th": eleventh_grd,
        "12th": twelfth_grd
})
reading_scores = math_scores[['9th', '10th', '11th', '12th']]
reading_scores.index.name = "School"

reading_scores

                             9th       10th       11th       12th
School
Bailey High School     77.083676  76.996772  77.515588  76.492218
Cabrera High School    83.094697  83.154506  82.765560  83.277487
Figueroa High School   76.403037  76.539974  76.884344  77.151369
Ford High School       77.361345  77.672316  76.918058  76.179963
Griffin High School    82.044010  84.229064  83.842105  83.356164
Hernandez High School  77.438495  77.337408  77.136029  77.186567
Holden High School     83.787402  83.429825  85.000000  82.855422
Huang High School      77.027251  75.908735  76.446602  77.225641
Johnson High School    77.187857  76.691117  77.491653  76.863248
Pena High School       83.625455  83.372000  84.328125  84.121547
Rodriguez High School  76.859966  76.612500  76.395626  77.690748
Shelton High School    83.420755  82.917411  83.383495  83.778976
Thomas High School     83.590022  83.087886  83.498795  83.497041
Wilson High School     83.085578  83.724422  83.195326  83.035794
Wright High School     83.264706  84.010288  83.836782  83.644986

## Scores by School Spending

* Create a table that breaks down school performances based on average Spending Ranges (Per Student). Use 4 reasonable bins to group school spending. Include in the table each of the following:
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)

In [572]:
# Sample bins. Feel free to create your own bins.
spending_bins = [0, 585, 615, 645, 675]
group_names = ["<$585", "$585-615", "$615-645", "$645-675"]

In [575]:
# create spending bins

df_combined['spending_bins'] = pd.cut(df_combined['budget']/df_combined['size'], spending_bins, labels = group_names)


#group by spending
by_spending = df_combined.groupby('spending_bins')


# #calculations
# avg_math = by_spending['math_score'].mean()
# avg_read = by_spending['reading_score'].mean()
# pass_math = merged_df[merged_df['math_score'] >= 70].groupby('spending_bins')['Student ID'].count()/by_spending['Student ID'].count()
# pass_read = merged_df[merged_df['reading_score'] >= 70].groupby('spending_bins')['Student ID'].count()/by_spending['Student ID'].count()
# overall = merged_df[(merged_df['reading_score'] >= 70) & (merged_df['math_score'] >= 70)].groupby('spending_bins')['Student ID'].count()/by_spending['Student ID'].count()

Percent_M = []
Percent_R = []

avg_mlt=df_combined['math_score'].mean()

avg_rlt= df_combined['reading_score'].mean()


#Percent_M = df_schools.loc[df_combined['math_score'] >=70,:]
#Mathh = Percent_M['math_score'].count() / students_value * 100



#Percent_R = df_schools.loc[df_combined['reading_score'] >=70,:]
#Read = Percent_R['reading_score'].count() / students_value * 100


#overall_pass = (len(Mathh + Read)) / 2

            
# df build            
scores_by_spend = pd.DataFrame({
    'Average Math Score': avg_mlt,
    'Average Reading Score': avg_rlt})
#     '% Passing Math': sch_distr,
#     '% Passing Reading': pass_read,
#     "Overall Passing Rate": overall_pass})

scores_by_spend
by_spending
# scores_by_spend.index.name = "Per Student Budget"
# scores_by_spend = scores_by_spend.reindex(group_name)

ValueError: If using all scalar values, you must pass an index

## Scores by School Size

* Perform the same operations as above, based on school size.

In [533]:
# Sample bins. Feel free to create your own bins.
size_bins = [0, 1000, 2000, 5000]
group_names = ["Small (<1000)", "Medium (1000-2000)", "Large (2000-5000)"]

## Scores by School Type

In [576]:
# create size bins
bins = [0, 999, 1999, 99999999999]
group_name = ["Small (<1000)", "Medium (1000-2000)" , "Large (>2000)"]
merged_df['size_bins'] = pd.cut(merged_df['size'], bins, labels = group_name)

#group by spending
by_size = merged_df.groupby('size_bins')

#calculations 
avg_math = by_size['math_score'].mean()
avg_read = by_size['math_score'].mean()
pass_math = merged_df[merged_df['math_score'] >= 70].groupby('size_bins')['Student ID'].count()/by_size['Student ID'].count()
pass_read = merged_df[merged_df['reading_score'] >= 70].groupby('size_bins')['Student ID'].count()/by_size['Student ID'].count()
overall = merged_df[(merged_df['reading_score'] >= 70) & (merged_df['math_score'] >= 70)].groupby('size_bins')['Student ID'].count()/by_size['Student ID'].count()

            
# df build            
scores_by_size = pd.DataFrame({
    "Average Math Score": avg_math,
    "Average Reading Score": avg_read,
    '% Passing Math': pass_math,
    '% Passing Reading': pass_read,
    "Overall Passing Rate": overall


scores_by_size.index.name = "Total Students"
scores_by_size = scores_by_size.reindex(group_name)

#formating

SyntaxError: invalid syntax (<ipython-input-576-1700c44cbd27>, line 26)

* Perform the same operations as above, based on school type.

In [597]:
# group by type of school
by_type= df_combined.groupby('type')

#calculations 
avg_math = by_type['math_score'].mean()
avg_read = by_type['math_score'].mean()
# pass_math = df_combined[by_type['math_score'] >= 70].groupby('type')['Student ID'].count()/by_type['Student ID'].count()
# pass_read = df_students[by_type['reading_score'] >= 70].groupby('type')['Student ID'].count()/by_type['Student ID'].count()
# overall = df_students[(by_type['reading_score'] >= 70) & (merged_df['math_score'] >= 70)].groupby('type')['Student ID'].count()/by_type['Student ID'].count()

# df             
scores_by_type = pd.DataFrame({
    "Average Math Score": avg_math,
    "Average Reading Score": avg_read,
     '% Passing Math': avg_math,
    '% Passing Reading': avg_read,
    "Overall Passing Rate": avg_math})

df.groupby(['columns'])

scores_by_type

,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
type,,,,,
Charter,83.406183,83.406183,83.406183,83.406183,83.406183
District,76.987026,76.987026,76.987026,76.987026,76.987026